version: "3"

services: 
  mongodb:
    container_name: mongodb-container
    image: mongo:3
    restart: always
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - "27017:27017"
  app:
    build: .
    command: yarn dev:watch
    ports:
      - 5050:5050
    environment:
      MONGO_URL: mongodb://mongodb:27017/clean-node-api
      PORT: 5050
      JWT_SECRET: 3ccd74ad43d8ce7afe36f2a71a365e6a6381248d2c02654177e568e7d40e590f
    volumes:
      - ./:/app
      - app_node_modules:/app/node_modules
    links:
      - mongodb
    depends_on:
      - mongodb

volumes:
  app_node_modules: {}